sequential: false

variables:
  batch_size: [32, 64, 128]
  model_configs: ['DNNProxy/models/gpt2_l.json', 'DNNProxy/models/gpt2_xl.json']

  partition: ["short"] # Baldo
  # partition: ["eth", "ib"]

jobs:
  - config: "baldo_gpu_test"
    config_jobs:
      - tag: "pytorch_stats_{model_configs}"
        command: "python3 DNNProxy/python/model_stats.py {model_configs} --batch_size={batch_size} --device='cuda'"
  # - config: "{partition}_{nodes}nodes"
  #   config_jobs:
  #     - tag: "{models_hardcoded}"
  #       command: "mpirun -np {nodes} {models_hardcoded} {models} {num_buckets}"
